### ISSUE TITLE
Confuse of AT+RFPOWER? command

### ISSUE THREAD

**Issue by PowerfulCat** [espressif/esp-at#255] opened 2019-11-01 01:51 UTC
Environment
- idf 3.3
- at 1.2.0
AT+RFPOWER?
+RFPOWER:-4,7,2,2

The wifi_power value read through this command is the dBm value, while the remaining three values are enumerate values. Is this the original intention of the design?

**Comment by xcguang** [comment] 2019-11-01 01:58
We have fixed it in the latest master branch, which will be released in the near two days.

**Comment by PowerfulCat** [comment] 2019-11-01 02:26
:)

**Comment by xcguang** [comment] 2019-11-01 04:02
the unit of the first value is dBm; the last three ones are power level; this is caused by different module APIs of the esp-idf.

Parameters:
- **\<wifi_power>**: range [40, 82], the unit is 0.25dBm, for example, if the value is 78, then RF max power is 78*0.25 dBm=19.5dBm
- **\<ble_adv_power>**: RF TX Power of BLE advertising, range: [0, 7]
    - 0:7dBm
    - 1:4dBm
    - 2:1dBm
    - 3:-2 dBm
    - 4:-5 dBm
    - 5:-8 dBm
    - 6:-11 dBm
    - 7:-14 dBm
- **\<ble_scan_power>**: RF TX Power of BLE scanning, range:  [0, 7], the same as **\<ble_adv_power>**
- **\<ble_conn_power>**: RF TX Power of BLE connecting, range:  [0, 7], the same as **\<ble_adv_power>**

**Comment by xcguang** [comment] 2019-11-01 04:05
+RFPOWER:-4,7,2,2    
`-4` is incorrect, which we fixed is.

**Comment by xcguang** [comment] 2019-11-06 02:08
We have released it, please try again.

**Closed** 2020-01-09 06:04 UTC
